image: php:7.1.1

pipelines:
    custom:
        init:
            - step:
                script:
                  - git clone https://github.com/git-ftp/git-ftp.git
                  - cd git-ftp
                  - git checkout 1.4.0
                  - make install
                  - cd ..
                  - git ftp init --user $FTP_USER --passwd $FTP_PASSWORD $FTP_SERVER
    branches:
        production:
            - step:
                deployment: production
                caches:
                    - node
                    - composer
                script:
                    # composer
                    - apt-get update && apt-get install -y unzip
                    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                    - composer install
                    # node
                    - apt-get install -y gnupg
                    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
                    - apt-get install -y nodejs
                    # git
                    - apt-get install -y git
                    # front
                    - npm -v && node -v
                    - npm install gulp-cli -g
                    - npm ci
                    - gulp
                    # deploy
                    - git clone https://github.com/git-ftp/git-ftp.git
                    - cd git-ftp
                    - git checkout 1.4.0
                    - make install
                    - cd ..
                    - git status
                    - git diff
                    - git ftp push --force --user $FTP_USER --passwd $FTP_PASSWORD $FTP_SERVER