image: node:10.9.0

pipelines:
    custom:
        init:
            - step:
                script:
                  - git clone https://github.com/git-ftp/git-ftp.git
                  - cd git-ftp
                  - git checkout 1.4.0
                  - make install
                  - cd ..
                  - git ftp init --user $FTP_USER --passwd $FTP_PASSWORD $FTP_SERVER
    branches:
        production:
            - step:
                deployment: production
                caches:
                    - node
                script:
                    - npm -v && node -v
                    - npm install gulp-cli -g
                    - npm ci
                    - gulp
                    - git clone https://github.com/git-ftp/git-ftp.git
                    - cd git-ftp
                    - git checkout 1.4.0
                    - make install
                    - cd ..
                    - git status
                    - git diff
                    - git ftp push --force --user $FTP_USER --passwd $FTP_PASSWORD $FTP_SERVER