web:
  build: docker
  links:
    - mysql:mysql
  ports:
    - "80:8080"
  volumes:
    - ./www:/var/www/html
    - ./config.php:/var/www/html/config.php
    - ./caronafametro_client_credentials.json:/var/caronafametro_client_credentials.json

mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./.data/db:/var/lib/mysql"